// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrzgmlyyjflzuyjyihka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yemdtbHl5amZsenV5anlpaGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzg2NTgsImV4cCI6MjA1ODg1NDY1OH0.GTtQKFBS4yASQA5Wba6KbLL633xauBy-1et6tJGATyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);